### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by cyberzilla** [cristianefe/MySQLTunnel#4]
**Notice: Trying to get property of non-object in /opt/lampp/htdocs/tunnel/NEW/tunnel.class.php on line 22
MysqlTunnelClient Object ( [url] => http://localhost/tunnel/NEW/remote.tunnel.php [errors] => Array ( ) [num_rows] => 0 [dbData:MysqlTunnelClient:private] => Array ( [host] => localhost [user] => root [pass] => [db_name] => testingDB [port] => 3306 ) [result:MysqlTunnelClient:private] => )** 

my configuration:
```
include  'tunnel.class.php';
$cfg = array('tunnel_url' => 'http://localhost/tunnel/NEW/remote.tunnel.php',
		'db_data' => array(
			'host' => 'localhost',//default is localhost
			'user' => 'root',
			'pass' => '',
			'db_name' => 'testingDB',
			'port' => '3306'));//default mysql port is 3306

$mysql = new MysqlTunnelClient($cfg);
$query = "SELECT * FROM user";
$q = $mysql->query($query);
print_r($q);
```

**Comment by backendrulz** [comment]
Sorry about that! is fixed now.

**Comment by cyberzilla** [comment]
Many Thanks, Working like charm
